### ISSUE TITLE
Database backup for fsek/web clones more than the rails app

### ISSUE THREAD

**Issue by lham** [fsek/web#123]
The sql dumps created by the backup contains all the databases within our mysql server. While it's a good idea to backup everything it seems unnecessary as we don't use the majority of the databases anymore. 

Should we limit the backup to the databases connected to out current rails app? (i.e. db/fsek_production and db/fsek_dev)

Should we do an "archiving backup" and the remove the unused databases from mysql?

**Comment by jforberg** [comment]
I'd say please leave the old databases in Mysql because in general we are really bad at archiving our old data and I could easily see it get lost if all we had was a dump somewhere.

But we don't have to take regular backups anymore, I agree. It's also better to just backup one database at a time because it's easier to restore if needed.

**Comment by davidwessman** [comment]
Someone who wanna look at this? :)

**Comment by davidwessman** [comment]
Are the database backup setup right now?
How was it done before?

**Comment by jforberg** [comment]
We only backup the tables that are considered 'live', as defined by a plain-text file in /root/bin.

**Comment by davidwessman** [comment]
Nice, didn't find it before ;) (didn't look well enough either!
