### ISSUE TITLE
Permissions: handle errors

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#153]
We need to show people what happens if their record is not found or they have to log in and so on.

How do we do this?

**Comment by jforberg** [comment]
Use exceptions

* Record not found => ``fail ActiveRecord::RecordNotFound`` or maybe ``fail ActionController::RoutingError`` depending on taste
* Not logged in => ``fail CanCan::AccessDenied``

Then rescue from these exceptions in ApplicationController and do the right thing. Usually render a page with some useful text or even just ``render :text => 'some message', :layout => true``.

**Comment by davidwessman** [comment]
https://github.com/fsek/web/blob/master/app/controllers/application_controller.rb
I did something like this for the AccessDenied:
```
rescue_from CanCan::AccessDenied do |ex|
    if current_user.nil?
      redirect_to :new_user_session, alert: ex.message
    else
      redirect_to :root, alert: ex.message
    end
  end
```

**Comment by jforberg** [comment]
@davidwessman Looks good apart from one thing:

redirect_to will send HTTP code 302 which is not right. 302 implies that the resource was "Found" at another address but here we are denying them the resource. So HTTP 403 would be more appropriate. Then you need to render instead of redirect_to because we can't set the status code from a redirect_to.

**Comment by davidwessman** [comment]
render for both cases? Like :
```
if current_user.nil?
  render :new_user_session, status: 302, alert: ex.message
else
  render :root, alert: ex.message
end
```
(Just guessed the status thing, perhaps there is a symbol instead.)

**Comment by jforberg** [comment]
@davidwessman Maybe you are "supposed" to know what the status codes are ;) In any case "found" doesn't tell you more than "302" if you didn't know the code in the first place.

Well, that may or may not work.

The problem with render is that it needs all the correct instance variables to be set. And the older code just **loves** instance variables. I'd just use a redirect_to for that.

The reason render works for 403 is that it's an exceptional condition, it's not supposed to happen because you have to manually enter a locked address or maybe have a faulty view. In any case it's not a expected error so we don't have to give a nice page but we can just have a little box that says "you did something you were not supposed to"

This is what I would do:

```
render :text => 'You did something you were not supposed to do', :status => 403, :layout => true
```

**Comment by jforberg** [comment]
Actually, it's wrong for another reason. You can't pass any content with an HTTP 302, the code just means "go to this page instead". It also implies a temporary redirect, not cacheable (301 is a permanent redirect).
