### ISSUE TITLE
Console: Dev and Prod

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#156]
I cannot access the console on either development or production (on main or on deploy).

```
/usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find railties (>= 0) amongst [bundler-1.7.6, bundler-unload-1.0.2, executable-hooks-1.3.2, gem-wrappers-1.2.7, hike-1.2.3, modernizr-2.6.2, multi_json-1.11.0, rack-1.6.0, rubygems-bundler-1.4.4, rvm-1.11.3.9, sprockets-2.12.3, tilt-1.4.1] (Gem::LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
	from /usr/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'
	from /usr/local/bin/rails:22:in `<main>'
```

Just want to check the current state of the database, if the ```Permission```-table is created.

**Comment by jforberg** [comment]
You have a bug in your gem config. Also, you are running a six year old version of ruby. Mistake or time to update?

(Assuming debian-ish system) My advice is in general to stay far away from the system's own ruby, rails, rvm everything as they are generally crap. Instead install rvm direct from source, ruby from rvm and rails from gems. In particular, do not run your system's RVM. It is by definition broken (the whole point of rvm is to override the system ruby!) and will actually poison any user-level RVM you try to install.

E.g. to get a sane Ruby environment on Dirac you have to hack ``/etc/profile.d/rvm.sh`` so that it doesn't inject the system RVM into your environment. Add your username next to mine :)

**Comment by davidwessman** [comment]
This is on the server, via ssh.

**Comment by davidwessman** [comment]
Checked into the file, wasn't completely sure about the syntax.
```[ "$USER" == 'jforberg'  || "$USER" == 'dwessman' ] && return```?

**Comment by henrikssn** [comment]
@jforberg rbenv is a better solution as that is what we use to install gems in production. It also contains the exactly same ruby version as used in production. Use

    cd /home/deploy/dev/current && rbenv exec bundle exec rails c development
    cd /home/deploy/production/current && rbenv exec bundle exec rails c production
to get to the consoles for dev/production.

**Comment by jforberg** [comment]
@henrikssn rbenv would also work, rvm and rbenv do essentially the same thing.

@davidwessman ``man test``. Or just go with @henrikssn solution which is maybe easier.

**Comment by davidwessman** [comment]
```-bash: rbenv: command not found```

**Comment by davidwessman** [comment]
@jforberg Are you running your own RVM then?

**Comment by henrikssn** [comment]
@davidwessman You need to "install" rbenv https://github.com/sstephenson/rbenv#basic-github-checkout

**Comment by jforberg** [comment]
@davidwessman yes I run rvm because that's the tool I'm familiar with. Rbenv does the same thing.
