### ISSUE TITLE
Google Analytics (Or similar)

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#168]
~~Need some fix for the Turbolinks.~~
We should implement Google Analytics - when I read into it a while ago there is a problem when rendering pages via Turbolinks, because it will not count as a page load.

**Comment by jforberg** [comment]
I don't get it.

Do you want us to enable GA or do you have a problem with turbolinks and GA? Pls clear

**Comment by jforberg** [comment]
Ok, much clearer :)

GA is not as useful as it once was, since it relies on the client not blocking third-party JS. With browser plugins such as Ghostery getting more popular, a lot of clients are now blocking software like GA that aims to track and identify clients.

I myself don't accept any third-party cookies or JS, mostly because I'm a very paranoid person and I don't like the idea of Google tracking me across the web.

Maybe you don't care or think that the percentage of users doing this is not significant (probably true, at least for the near future). An alternative would be server-side analytics which the user can't block.

**Comment by davidwessman** [comment]
Okay - but it would be nice to have some statistics - what pages people are visiting. 
I do not want to track individuals. 
Is there anything similar to this? Otherwise we can just close this :)

**Comment by jforberg** [comment]
@davidwessman I'm not saying GA is bad. Go with GA, it's probably the simplest solution :) You should just be aware that not everyone will show up in the statistics.

**Comment by davidwessman** [comment]
Okay, then I know what you mean.

Well the absolute numbers is not really interesting, but some pointers can be good 😄 
We'll keep this open.

**Comment by henrikssn** [comment]
@jforberg There are solutions for tracking non-JS users with GA. For example

http://www.simoahava.com/analytics/track-non-javascript-visits-google-analytics/
