### ISSUE TITLE
How to do a deploy?

### ISSUE THREAD

**Issue by jforberg** [fsek/web#224]
How do I deploy code with the new system?

Specifically, how do I handle these cases:

1. I need to do some kind of manual intervention, like migrate the database in interactive mode or such in connection with a new release.

2. I need to roll back a previous deploy which didn't work right.

**Comment by davidwessman** [comment]
Right now we only have local deployment.
@henrikssn installed Samson this spring but thought it was kind of a hassle to setup and use.
So he thought it would be better to use Capistrano for deployment and asking Travis CI to call Capistrano.

I haven't been able to setup Travis to deploy properly, right now I'm trying a bit with Circle CI.

To deploy:
Checkout the branch you want to deploy, make sure the Github version is up to date as well.
Call `cap *environment* deploy` (where *environment* can be `production, staging, dev`).

To rollback:
`cap production deploy:rollback' (I haven't tried this completely).

I do not think this setup allows for the manual intervention, atleast not as we configured right now.
You can set up a lot of different tasks however, might be able to solve it with that.

I also haven't added the reload of passenger/nginx since it wasn't configured properly when I worked with it.

So this is kind of WIP ;) Any suggestions would be great 😄

**Comment by jforberg** [comment]
Well, that sounds ok I guess. With rollback, can I specify a gitref or is it always "the previous ref"?

I've used heroku in the past which had a really simple and pragmatic build system. All you did was push a ref to some git repository, and it would take that and deploy it. Downtime was usually like 5 seconds with no connections dropped. All migrations were manual which IMO is definitely the only right way to do it with a database like mysql which doesn't have real schema migrations (meaning if the migration fails for any reason you will be left with a broken database state). Does cap support this workflow?

Me, I'm really not interested in build systems. I prefer it when they just stay out of my way :). If capistrano doesn't support manual deploys then that is a problem IMO. It's not so often that you have to resort to manual deploys but when you do, you are ususally not in a mood to fight with the build system.

Disclaimer: I'm a bit cranky because I spent my whole day at work fighting with my company's build system...

**Comment by davidwessman** [comment]
Uhm I think you can specify a certain ref, it will keep the 5 latests builds (can be edited as well)

**Comment by davidwessman** [comment]
http://capistranorb.com/documentation/getting-started/flow/
By doing scripts you can do something like you said, you can define different stages in the deployment.
