### ISSUE TITLE
Git: Some structure ideas

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#233]
Using a Git-flow can make structuring easier.
#206 takes up the ``git rebase -i`` and ``git add -p ``commands.

It could also be a good idea to append the "category" of your branch:
  -``feature-car-rental``
  -``hotfix-rent``

Not like rules, but can give some transparency to the commit history 😄 

Worth reading:
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by jforberg** [comment]
This is not a bad idea, but I don't agree with everything the article says. He uses a permanent integration branch which he calles "develop". This implies a lot of other rules like merge windows, a release manager role etc. Up until now, we have been able to handle everything by integrating each feature separately which is *much* simpler on us. So I propose to keep doing this as much as possible.

If you don't have merge windows, the distinction between fix-branches and feature branches sort of disappears since everything is integrated against master. So while you may want to do it for "consistency" or to give a hint to the reader, there is no semantic disinction.

What I *do* think would be very useful is a distinction between stable and unstable branches. Unstable branches are the ones we are allowed to force-push. At my company we use this branching convention (replace subject with something descriptive):

pre-topic/subject: unstable topic branch
topic/subject: stable topic branch
pre-fix/subject: unstable fix branch; I work in embedded software where there is no such thing as a "hotfix" :)
fix/subject: stable fix branch
user/johanfb/subject: your own namespace, do what you want.

I've basically started using this convention here as well, claiming the jforberg/ namespace.

It tends to be that people mostly use the pre-* variant of branches because being able to rephrase your patches is *really* convenient. But we always leave a stable branch behind for reference.

**Comment by davidwessman** [comment]
Very valid arguments 😄 
The workflow now seems good, especially when learning `git rebase` and `git add -p` to get clearer commits. 😄
