### ISSUE TITLE
Use mariadb instead of mysql

### ISSUE THREAD

**Issue by kotrfa** [fsek/web#240]
MariaDB can be used as a drop-in replacement for MySQL. The reason for it is it's bigger support from open-source community and Oracle's unfortunate attitude to MySQL development.

MariaDB is used by biggest projects on the world such as Wikipedia, Google or major Linux distributions such as RedHat or SUSE, supports plentiful of features while still being highly efficient (and just [wins](https://mariadb.com/kb/en/mariadb/network-world-tested-6-free-databases-mariadb-wins-the-test/)).

As a matter of fact, I am currently running current master branch on MariaDB without problems (as far as I can see). I hadn't to change a thing in configuration - only installed and ran MariaDB while using this `database.yml` file:
```
default: &default
  adapter: mysql2
  encoding: utf8
  database: fsektdb
  pool: 5
  username: root
  password: root_pswd
  host: 127.0.0.1
  port: 3306
```
and running `rake db:reset;rake db:create db:migrate permissions:load db:populate_test`. 

[10 reasons why to switch](https://seravo.fi/2015/10-reasons-to-migrate-to-mariadb-if-still-using-mysql)

**Comment by davidwessman** [comment]
Hmm, will you still use the `mysql2`and adapter?

Might need to look into the server setup as well. Currently running Debian Jessie version 8 I think.

This could be a long-term goal, I like supporting OpenSource-solutions (y)

**Comment by kotrfa** [comment]
Yes, you do, since MariaDB is binary compatible with MySQL (at least up to some versions). This feature is language agnostic, by the way.

According to this `[2015-04-26] 10.0.16 released as part of Debian 8 "Jessie"` from official [Debian Wiki](https://wiki.debian.org/Teams/MySQL/MariaDB), MariaDB should be in official repositories of Jessie, so that shouldn't be a problem and simple `apt-get install mariadb-server` should work.

**Comment by jforberg** [comment]
Mariadb is a fork of Mysql. The fork was made when Oracle bought Sun some years ago, along with some other forks such as openoffice -> libreoffice, solaris -> illumos. The forks were done because basically, some open-source progammers despise Oracle and just don't trust them. Decide for yourself.

I use mariadb locally since that is the mysql implementation packaged by archlinux. It is similar if not identical to mysql. Both are open-source.

I would prefer that we use the database that is packaged with the system unless there is a reason not to. We have much more pressing concerns IMO.

If we **are** going to change to another database then I would much prefer that we choose **postgres** which has very real benefits over mysql. See for instance http://stackoverflow.com/questions/110927/would-you-recommend-postgresql-over-mysql#answer-112805

**Comment by kotrfa** [comment]
Same here - I am using Arch Linux too so MariaDB was a clear choice. As I said, MariaDB should be in official repositories and hence it should be painless to switch to it. 

I haven't a lot of experience with Postgres and cannot say about it a lot. But here we are talking about changing the database even with it's underlying settings, which I have no idea how they work in RoR. If it's as simple as in Django, then it doesn't matter. Great post by the way.

**Comment by jforberg** [comment]
Painless: in theory yes. But consider that we have many different applications using the database. Postfix, gallery2, wordpress etc. all use it in parallel. Are we sure that they all support mariadb and will continue doing so? The simplest thing is just to keep using mysql for now, I think.

Switching the database would not be that hard because like I said, we currently only use the very simplest most basic features of our database. And like in django, for these very simple cases the adapter can actually generate the queries for us.

But I don't think switching is necessary at this point.

**Comment by jforberg** [comment]
Hehe, realised I maybe sound a bit stern. 

I appreciate that you are coming with suggestions, I just think we will all be happiest if we focus on writing new features for now, not messing with the stack :)

Also, welcome onboard. Great to have you here!

**Comment by kotrfa** [comment]
No problem with the tone, I've been warned. 

Agree, we can close this then :) .
