### ISSUE TITLE
RSpec: should or expect

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#283]
We had the discussion before that the `should`-matcher is looking better and we decided to use it.
While updating our RSpec-Configuration I tried to enable `disable_monkey_patching`, which made all assertions with `should` fail.

The `should`-method is monkey-patched onto every object and can give some strange errors because RSpec does not own every object.
Ref:
https://www.relishapp.com/rspec/rspec-expectations/v/3-0/docs/syntax-configuration

There is a `transpec`-gem for easily changing all the specs.
http://yujinakayama.me/transpec/

Or we can continue with the monkey-patched version.

**Comment by jforberg** [comment]
This is (of course) the reason why rspec-core migrated from should to expect. In my opinion they should have dropped ruby completely and written a proper DSL so they wouldn't have to hack the core classes.

At this point, although should is a bit evil I think it works well enough. I have yet to see any errors in code I work on that are related to should. I expect any such bugs would be pretty straightforward to debug.

So I vote to keep should for the readability (which is the whole point of rspec, otherwise we would just use Test::Unit which is much simpler).

**Comment by davidwessman** [comment]
Yeah, if we do not run into any other errors we can keep on going like this.
