### ISSUE TITLE
Global references

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#298]
We have a lot of dynamic models which are used in the layout at the moment.
I do not like the way the contact-links works since they do one query each and looks terrible, also doesn't work when the `Contact` gets a new title. (I think I wrote all of the code, never got around to change it).

###How should we do this referencing? 
- For the `Menu` we load all the resources in the view, could you load them in ApplicationController or something? 
- How would you load the `Spindelman` contact used in the footer? 

For some dynamic things such as the rules for renting the car I have created a `Constant` called `rent_terms` which has the id of the rule `Document` as a value.

What do would be the best solution?

**Comment by jforberg** [comment]
No good way to load them all at the same time, as would be best. But the database is very quick at these kinds of lookups, what usually takes time is the somewhat inefficient templating code.

Have you considered fragment caching? Basically what you do is cache a part of the DOM tree and set it to expire on an object, e.g. the Contact record. So you load the record from database and unless it has changed since the last cached version you can just reuse the cahced fragment.

http://guides.rubyonrails.org/caching_with_rails.html#fragment-caching

**Comment by davidwessman** [comment]
Implemented some fragment caching for the menus in #299, not sure if it works though.

**Comment by jforberg** [comment]
You can usually see in the logs / console output if it is actually reading the cache or just rendering it again.

**Comment by davidwessman** [comment]
Merged #299 with a view object called `GlobalMenu` and used caching for menus.
