### ISSUE TITLE
Seeding data

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#348]
It would be nice to have seeding data for different environments but also for things that should be in the database all the time. It could be done with the link below, and then we could get rid of the [rake task](https://github.com/fsek/web/blob/master/lib/tasks/tests_data.rake) I have used for a while. 

https://archive.dennisreimann.de/blog/seeds-for-different-environments/

**Comment by jforberg** [comment]
db:seed is for data that should always be in the database. db:seed is run as the last step of db:setup.

Putting "test" data in seeds is a bit non-standard IMO. I think the current system works well.

Also, using seeds for the test environment will probably not work since the database may be truncated anywhere in the test suite. Test that depend on data being in the database should put it there explicitly.

**Comment by jforberg** [comment]
Also, for general "test" data one approach would be to just download one of the production database dumps and use that. This is how I have been working for the most part. Putting this in a rake task would be simple, if a task is desired. User accounts should probably be omitted or have their password hashes removed.
