### ISSUE TITLE
CSS > SASS/SCSS

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#48]
Would be great to use SCSS, atleast I like that structure more :) 
http://css2sass.herokuapp.com/

Pretty smooth tool

**Comment by lham** [comment]
I've been thinking about refactoring the whole design, including the css. It's kinda broken in a lot of places now.

**Comment by Zofz** [comment]
Yepp, everything is like overridden with !important marks.

**Comment by jforberg** [comment]
Sass is great. Also since it's statically compiled there is no downside.

One problem though: one of the great things about Sass is that you can work with your CSS framework in source form, i.e. tweak variables etc. before it's even compiled. So you don't have to pile !important rules on top of framework rules you want to override.

The problem is, Bootstrap (the CSS framework we use) is written in Less, not Sass. Although I think there is now a Sass port.

https://github.com/twbs/bootstrap-sass

**Comment by Zofz** [comment]
Does indeed sound good - @lham, do you have time to look more at this?

**Comment by lham** [comment]
Ye, I can take a look at it. @jforberg I've used the sass-port in another project, it works great!

**Comment by henrikssn** [comment]
There is also css.sass.erb which enables dynamic ruby inside of the sass files. Don't know if that is good practice however...

**Comment by jforberg** [comment]
@lham Great success.
@henrikssn That means no caching of your global css file :) recompiling on every request will take ages. Wouldn't use that unless I had to, but as usual the least ugly solution wins.

**Comment by davidwessman** [comment]
I installed https://github.com/twbs/bootstrap-sass and it seems to work.
Not sure if it is completely configured yet.
The old bootstrap-files are still in the vendor folder.

**Comment by davidwessman** [comment]
#222 closes this
