### ISSUE TITLE
Access Code

### ISSUE THREAD

**Issue by Zofz** [fsek/web#54]
I have implemented editing with an access_code on both Bilbokning and Cafebokning (since they allow users without logins).
Should we port this functionality into a separate resource?

We should get some way for non-members to sign up as well, for example this summer we want to allow all the new students to sign up to the website before they turn up in medcheck, perhaps we could build the access_code-feature to involve codes for signing up as well.

Ideas?

@fsek/admins

**Comment by henrikssn** [comment]
Why would we allow this without login?

For new users without medcheck there should be a separate role ("non-member"?) so that we can restrict their access. We could allow them to add themselves to the member role when they later pass a medcheck. Non-members could still e.g. work in the cafe. They should not get access to any documents or the gallery.

**Comment by Zofz** [comment]
The car can be rented without being a member of the F-guild, same thing with working in the cafe.

Allowing everyone to to sign up would definitely be an option, and then just confirm with medcheck.

**Comment by Zofz** [comment]
Move over to #59.
